---
services:
  chrony:
    image: nlp0/chrony:latest
    restart: unless-stopped
    environment:
      NTP_SERVERS: "ntp0.ntp-servers.net, ntp1.ntp-servers.net, ntp2.ntp-servers.net"
      NTP_POOLS: "0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org, 3.pool.ntp.org"
      ALLOW_CIDR: "192.168.0/24, 10.10.0/24"
    ports:
     - 123:123/udp
