name: docker Chrony
on:
  schedule:
    - cron: "0 5 * * 1-5"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: docker.io/nlp0/chrony:latest
  VER_LOG: version.txt

jobs:
  push:
    name: Publish to docker hub registry
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}

  check:
    needs: [push]
    name: Pull image
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        run: |
          docker run -i --rm  --entrypoint versions ${{ env.IMAGE_NAME }} > ${{ env.VER_LOG }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: N-LP0
          author_email: ${{ secrets.author_email.AUTHOR_EMAIL }}
          message: "upd"
          add: "version*"
